FROM python:3.11-slim

WORKDIR /app

RUN apt update && apt install -y build-essential

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
